on:
  pull_request:
    branches-ignore:
      - main

jobs:
  Pre_Merge_Checks:
    uses: thalluripk/github-workflows/.github/workflows/useme.yml@main
    with:
      branch-name: $env:GITHUB_REF_NAME
