on:
  push:
    branches-ignore:
      - main
  pull_requests:
    branches-ignore:
      - main

jobs:
  hello_world_job:
    uses: thalluripk/github-workflows/.github/workflows/useme.yml@main
    with:
      branch-name: "Pranati Thalluri"
