on:
  workflow_call:
    inputs:
      user:
        type: string
        required: true
        description: enter user name

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: thalluripk/github-workflows/.github/actions/action-1
        with:
          who-to-greet: ${{inputs.user}}
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
